CREATE TABLE IF NOT EXISTS bolletta_templates (
  scope_key VARCHAR(64) NOT NULL PRIMARY KEY,
  overrides_json JSON NOT NULL,
  revision INT UNSIGNED NOT NULL DEFAULT 0,
  updated_by VARCHAR(100) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
